{
 "title": "Fae.dev worker queues",
 "description": "Graphs for Bull Queues \n\nhttps://github.com/UpHabit/bull_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "prefix",
    "label": "env",
    "query": "label_values(bull_queue_waiting, prefix)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queues vs active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "length" }
   ],
   "targets": [
    {
     "expr": "sum(bull_queue_waiting{prefix=~\"$prefix\"}) by (prefix, queue) ",
     "legendFormat": "{{ queue }}"
    },
    {
     "expr": "sum(bull_queue_active{prefix=~\"$prefix\"}) by (prefix, queue) ",
     "legendFormat": "{{ queue }} active"
    }
   ]
  },
  {
   "title": "Queue States",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bull_queue_active{prefix=~\"$prefix\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(bull_queue_waiting{prefix=~\"$prefix\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(bull_queue_delayed{prefix=~\"$prefix\"})",
     "legendFormat": "Delayed"
    }
   ]
  },
  {
   "title": "Average durations",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bull_queue_complete_duration { prefix=~\"$prefix\" }) by (queue)",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Average duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(bull_queue_complete_duration { prefix=~\"$prefix\" }) by (queue)",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Queue States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bull_queue_completed{prefix=~\"$prefix\"}[5m])) * 60",
     "legendFormat": "Complete Rate"
    },
    {
     "expr": "sum(rate(bull_queue_failed{prefix=~\"$prefix\"}[5m])) * 60",
     "legendFormat": "Fail Rate"
    },
    {
     "expr": "sum(bull_queue_active{prefix=~\"$prefix\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(bull_queue_waiting{prefix=~\"$prefix\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(bull_queue_delayed{prefix=~\"$prefix\"})",
     "legendFormat": "Delayed"
    },
    {
     "expr": "sum(bull_queue_failed{prefix=~\"$prefix\"})",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}