{
 "title": "Infra - instances",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "DC",
    "query": "label_values(nomad_client_uptime, datacenter)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(nomad_client_uptime, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_total{datacenter=~\"$datacenter\", host=~\"$host\"}) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_used_percent{datacenter=~\"$datacenter\", host=~\"$host\"}) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sum(nomad_client_host_memory_used{datacenter=~\"$datacenter\", host=~\"$host\"}) by (host) / sum(nomad_client_host_memory_total{datacenter=~\"$datacenter\", host=~\"$host\"}) by (host)) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Disk inodes",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_inodes_percent{datacenter=~\"$datacenter\", host=~\"$host\"}) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}